version: '3.3'

services:
  zenoh-router:
    image: eclipse/zenoh
    container_name: zenoh-router
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./zenoh-docker:/root/.zenoh
    command: -c /root/.zenoh/config/zenoh.json5