name: Clang Format Apply

on:
  pull_request:
    branches:
      - main
      - dev
      - 65-task-actions-workflow-update

jobs:
  format:
    name: Format Code
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: false
          ref: ${{ github.head_ref }}

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Run clang-format
        run: |
          find . -name '*.cpp' -o -name '*.h' | xargs clang-format -i -style=file

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'style: apply clang-format changes'
          branch: ${{ github.head_ref }}